    - name: Copy the system information script to /etc/profile.d/
      copy:
        src: /opt/ansible/scripts/motd.sh
        dest: /etc/profile.d/motd.sh
        mode: '0755'

    - name: Run the system information script
      command: /etc/profile.d/motd.sh
      register: script_output

    - name: Display script output
      debug:
        msg: "{{ script_output.stdout }}"


    - name: Copy the NRPE configuration file
      copy:
        src: files/nrpe.cfg
        dest: /opt/ansible/files/nrpe.cfg
        owner: root
        group: root
        mode: '0644'

    - name: Restart NRPE service
      systemd:
        name: nrpe
        state: restarted
        enabled: yes


