---
    - name: Clone Bugy Server repository
      ansible.builtin.git:
        repo: 'https://github.com/bugy/script-server.git'
        dest: /opt/bugy/script-server

    - name: Install Bugy Server dependencies globally
      ansible.builtin.command:
        cmd: python3.7 -m pip install -r /opt/bugy/script-server/requirements.txt
      args:
        chdir: /opt/bugy/script-server

    - name: Initialize Bugy Server
      ansible.builtin.command:
        cmd: python3.7 tools/init.py --no-npm
      args:
        chdir: /opt/bugy/script-server

    - name: Create systemd service file for Bugy Server
      ansible.builtin.copy:
        dest: /etc/systemd/system/bugy-server.service
        content: |
          [Unit]
          Description=Bugy Server
          After=network.target

          [Service]
          ExecStart=/usr/bin/python3.7 /opt/bugy/script-server/launcher.py
          WorkingDirectory=/opt/bugy/script-server
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd to apply new service
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start Bugy Server service
      ansible.builtin.systemd:
        name: bugy-server
        enabled: yes
        state: started

    - name: Copy Bugy Server conf.json to /usr/share/bugy/conf/
      ansible.builtin.copy:
        src: /opt/ansible/files/bugy-setup/files/conf.json
        dest: /opt/bugy/script-server/conf/conf.json
        mode: '0755'
