   
   
---

    - name: Install required packages
      ansible.builtin.yum:
        name:
          - python3
          - python3-venv
          - git
        state: present

    - name: Clone Bugy Server repository
      ansible.builtin.git:
        repo: 'https://github.com/bugy/script-server.git'
        dest: /opt/bugy/script-server

    - name: Create virtual environment
      ansible.builtin.command:
        cmd: python3 -m venv /opt/bugy/script-server/venv
      args:
        creates: /opt/bugy/script-server/venv/bin/python

    - name: Install Bugy Server dependencies
      ansible.builtin.command:
        cmd: /opt/bugy/script-server/venv/bin/pip install -r /opt/bugy/script-server/requirements.txt
      args:
        chdir: /opt/bugy/script-server

    - name: Create systemd service file for Bugy Server
      ansible.builtin.copy:
        dest: /etc/systemd/system/bugy-server.service
        content: |
          [Unit]
          Description=Bugy Server
          After=network.target

          [Service]
          ExecStart=/opt/bugy/script-server/venv/bin/python /opt/bugy/script-server/launcher.py
          WorkingDirectory=/opt/bugy/script-server
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd to apply new service
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start Bugy Server service
      ansible.builtin.systemd:
        name: bugy-server
        enabled: yes
        state: started

    - name: Ensure the directory /usr/share/bugy/scripts/ exists
      file:
        path: /usr/share/bugy/scripts/
        state: directory
        mode: '0755'  # Directory permissions (you can adjust this)


    - name: Copy bugy server scritps to /usr/share/bugy/scripts/
      copy:
        src: /opt/ansible/scripts/setup-menu-script.sh
        dest: /usr/share/bugy/scripts/setup-menu-script.sh
        mode: '0755'