---
- name: Install and configure HTTPD on web servers
  hosts: web_servers
  become: yes
  tasks:
    - name: Install httpd package
      yum:
        name: httpd
        state: present

    - name: Ensure httpd is started and enabled
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Deploy custom HTML file with hostname
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Welcome to My Web Server</title>
          </head>
          <body>
              <h1>Hello, Ansible!</h1>
              <p>This web server is configured using Ansible.</p>
              <p>Hostname: {{ inventory_hostname }}</p>
          </body>
          </html>
