    - name: Install httpd package
      yum:
        name: httpd
        state: present
  
    - name: Clean yum metadata
      command: yum clean metadata

    - name: Install PHP and extensions
      yum:
        name:
          - php
          - php-cli
          - php-fpm
          - php-mysqlnd
        state: present

    - name: Start and enable php-fpm service
      service:
        name: php-fpm
        state: started
        enabled: yes

    - name: Verify PHP version
      command: php -v
      register: php_version

    - name: Print PHP version
      debug:
        msg: "PHP version installed: {{ php_version.stdout }}"


        