---
    - name: Copy 10-php.conf to /etc/httpd/conf.modules.d/
      copy:
        src: /opt/ansible/files/webserver_config/10-php.conf
        dest: /etc/httpd/conf.modules.d/10-php.conf
        owner: root
        group: root
        mode: '0644'

    - name: Restart httpd service
      service:
        name: httpd
        state: restarted
