---

- name: Copy 10-php.conf to /etc/httpd/conf.modules.d/
  copy:
    src: /opt/ansible/files/webserver_config/10-php.conf
    dest: /etc/httpd/conf.modules.d/10-php.conf
    owner: root
    group: root
    mode: '0644'

- name: Replace text and colors in HTML file
  replace:
        path: /var/www/html/index.html
        regexp: 'Web Server 1'
        replace: 'Web Server 2'
  when: ansible_hostname == "web-server-2"

- name: Replace gradient colors in big-text
  replace:
        path: /var/www/html/index.html
        regexp: 'background: linear-gradient\(45deg, #1e90ff, #32cd32, #ffeb3b\);'
        replace: 'background: linear-gradient(45deg, #ff4500, #1e90ff, #8a2be2);'
  when: ansible_hostname == "web-server-2"

- name: Restart httpd service
  service:
    name: httpd
    state: restarted




## THis block of code to replace the iP of the database
- name: Copy the database IP from the controller to the webserver
  copy:
    src: /tmp/db_ip.txt
    dest: /tmp/db_ip.txt

- name: Read the IP address into a variable
  command: cat /tmp/db_ip.txt
  register: db_ip

- name: Replace databaseIP in register.php with the actual database IP
  replace:
    path: /var/www/html/register.php
    regexp: 'databaseIP'
    replace: "{{ db_ip.stdout }}"
