---
    - name: Ensure swap file exists
      ansible.builtin.command:
        cmd: fallocate -l 2G /swapfile
        creates: /swapfile

    - name: Set correct permissions on the swap file
      ansible.builtin.file:
        path: /swapfile
        owner: root
        group: root
        mode: '0600'

    - name: Setup the swap space
      ansible.builtin.command: mkswap /swapfile
      when: ansible_swaptotal_mb == 0

    - name: Enable the swap file
      ansible.builtin.command: swapon /swapfile
      when: ansible_swaptotal_mb == 0

    - name: Ensure swap file is present in /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: '/swapfile none swap sw 0 0'
        create: yes
