    - name: Install EPEL repository
      command: sudo amazon-linux-extras install epel -y
      when: ansible_facts.packages['epel-release'] is not defined

    - name: Download Snapd repository configuration
      get_url:
        url: https://bboozzoo.github.io/snapd-amazon-linux/amzn2/snapd.repo
        dest: /etc/yum.repos.d/snapd.repo

    - name: Install Snapd
      yum:
        name: snapd
        state: present

    - name: Enable and start Snapd service
      systemd:
        name: snapd
        enabled: yes
        state: started
      
    - name: Create custom profile script for PATH
      copy:
        dest: /etc/profile.d/snap_path.sh
        content: |
          #!/bin/sh
          export PATH=$PATH:/snap/bin
        mode: '0755'

    - name: Ensure Amazon Linux Extras repository is installed
      yum:
        name: amazon-linux-extras
        state: present

    - name: Enable PHP 7.4 in Amazon Linux Extras
      command: amazon-linux-extras enable php7.4
      args:
        creates: /etc/yum.repos.d/amzn2extra-php7.4.repo