---
- name: Ensure hostnames match inventory names
  hosts: localhost
  become: yes  # Use sudo to execute tasks with root privileges
  tasks:
    - name: Set hostname to match inventory name
      hostname:
        name: "Ansible-Node"

    - name: Update /etc/hostname
      lineinfile:
        path: /etc/hostname
        line: "ansible-controller"
        create: yes

    - name: Ensure the hostname is set in /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^127.0.0.1'
        line: "127.0.0.1 ansible-controller"
        create: yes
