---
- name: Install necessary tools
  hosts: localhost
  become: yes

  tasks:
    - name: Update all repositories
      yum:
        name: "*"
        state: latest

    - name: Install figlet
      yum:
        name: figlet
        state: present

    # Add more tasks here to install other tools
