    - name: Add Nagios admin user
      command: htpasswd -b /etc/nagios/passwd nagiosadmin {{ password }}
      vars:
        password: 'password'


    - name: Ensure Nagios command definition for check_nrpe
      blockinfile:
        path: /etc/nagios/objects/commands.cfg
        block: |
          define command{
              command_name        check_nrpe
              command_line        $USER1$/check_nrpe -H $HOSTADDRESS$ -c $ARG1$
          }
        marker: "# {mark} ANSIBLE MANAGED BLOCK check_nrpe"

    - name: Create Nagios configuration files
      template:
        src: nagios_template.cfg.j2
        dest: /etc/nagios/servers/{{ inventory_hostname }}.cfg

    - name: Ensure nagios.cfg includes servers directory
      lineinfile:
        path: /etc/nagios/nagios.cfg
        regexp: '^#cfg_dir=/etc/nagios/servers'
        line: 'cfg_dir=/etc/nagios/servers'
        state: present

    - name: Create configuration directory
      file:
        path: /etc/nagios/servers
        state: directory

    - name: Create Nagios configuration files
      template:
        src: nagios_template.cfg.j2
        dest: /etc/nagios/servers/{{ inventory_hostname }}.cfg


