    - name: Add Nagios admin user
      command: htpasswd -b /etc/nagios/passwd nagiosadmin {{ password }}
      vars:
        password: 'password'


    - name: Ensure Nagios command definition for check_nrpe
      blockinfile:
        path: /etc/nagios/objects/commands.cfg
        block: |
          define command{
              command_name        check_nrpe
              command_line        $USER1$/check_nrpe -H $HOSTADDRESS$ -c $ARG1$
          }
        marker: "# {mark} ANSIBLE MANAGED BLOCK check_nrpe"

    - name: Ensure nagios.cfg includes servers directory
      lineinfile:
        path: /etc/nagios/nagios.cfg
        regexp: '^#cfg_dir=/etc/nagios/servers'
        line: 'cfg_dir=/etc/nagios/servers'
        state: present

    - name: Create configuration directory
      file:
        path: /etc/nagios/servers
        state: directory

    - name: Create Nagios configuration files
      template:
        src: nagios_template.cfg.j2
        dest: "/tmp/{{ item }}.cfg"  # Temporary location on each host
      loop: "{{ groups['all'] }}"  # Loop over all hosts in the inventory (you can also limit this to specific groups)
      vars:
        ansible_host: "{{ hostvars[item].ansible_host }}"  # Ensure ansible_host is available

    # - name: Move configuration files to Nagios server
    #   copy:
    #     src: "/tmp/{{ item }}.cfg"
    #     dest: "/etc/nagios/servers/{{ item }}.cfg"  # Path on Nagios server
    #     owner: nagios  # You can adjust permissions if needed
    #     group: nagios
    #     mode: '0644'
    #     remote_src: true 
    #   delegate_to: "{{ inventory_hostname }}"  # Make sure this points to the Nagios server
    #   loop: "{{ groups['all'] }}"
    #   when: ansible_host is defined

    # - name: Synchronize configuration files from remote hosts to the Nagios server
    #   synchronize:
    #     src: "/tmp/{{ item }}.cfg"        # Source file on the remote host
    #     dest: "/etc/nagios/servers/{{ item }}.cfg"  # Destination on the Nagios server
    #     mode: pull  # This means the files are pulled from the remote hosts to the Nagios server
    #   delegate_to: "{{ inventory_hostname }}"  # Make sure this points to the Nagios server
    #   loop: "{{ groups['all'] }}"
    #   when: ansible_host is defined

    - name: Pause to ensure file creation
      pause:
        seconds: 5

    - name: Synchronize configuration files from remote hosts to the Nagios server
      synchronize:
        src: "/tmp/{{ item }}.cfg"        # Source file on the remote host
        dest: "/etc/nagios/servers/{{ item }}.cfg"  # Destination on the Nagios server
        mode: pull  # This means the files are pulled from the remote hosts to the Nagios server
      delegate_to: "{{ inventory_hostname }}"  # Make sure this points to the Nagios server
      loop: "{{ groups['all'] }}"
      when: ansible_host is defined