# nagios_setup/tasks/install_packages.yml
---
- name: Update yum cache
  yum:
    update_cache: yes


- name: Install httpd
  yum:
    name: httpd
    state: present

- name: Install required packages
  yum:
    name: "{{ packages }}"
    state: present
    vars:
      packages:
        - nagios
        - nagios-plugins-ping
        - nagios-plugins-disk
        - nagios-plugins-users
        - nagios-plugins-procs
        - nagios-plugins-load
        - nagios-plugins-swap
        - nagios-plugins-ssh
        - nagios-plugins-http

