- name: Enable and start Nagios service
  systemd:
        name: nagios
        enabled: true
        state: started

- name: Restart httpd service
  service:
        name: httpd
        state: restarted
        enabled: yes

- name: Restart Nagios service
  service:
        name: nagios
        state: restarted
        enabled: yes
