    - name: Update all repositories
      yum:
        name: "*"
        state: latest

    - name: Install figlet
      yum:
        name: figlet
        state: present


    - name: Install lolcat
      snap:
        name: lolcat
        state: present

    # Add more tasks here to install other tools

    - name: Install NRPE and Nagios plugins
      yum:
        name:
          - nrpe
          - nagios-plugins-ping
          - nagios-plugins-disk
          - nagios-plugins-users
          - nagios-plugins-procs
          - nagios-plugins-load
          - nagios-plugins-swap
          - nagios-plugins-ssh
          - nagios-plugins-nrpe 
          - nrpe
        state: present
