---
- name: Fetch files from all servers to control host
  hosts: all
  gather_facts: yes
  tasks:
    - name: Fetch file from the remote server to control host
      fetch:
        src: /tmp/{{ inventory_hostname }}.cfg  # Path to the config file on the remote servers
        dest: /tmp/ansible_fetched_files/{{ inventory_hostname }}.cfg  # Directory on the control node where files will be saved
        flat: yes  # Prevent directory structure from being recreated on the control node


- name: Copy configuration files to Nagios server
  hosts: nagios_server  # Target Nagios server
  gather_facts: true
  become: yes  # Elevate privileges to root
  tasks:
    - name: Ensure remote directory exists
      ansible.builtin.file:
        path: /etc/nagios/servers
        state: directory
        owner: nagios
        group: nagios
        mode: '0755'

    - name: Copy chat-server.cfg to Nagios server
      ansible.builtin.copy:
        src: /tmp/ansible_fetched_files/chat-server.cfg
        dest: /etc/nagios/servers/chat-server.cfg
        owner: nagios
        group: nagios
        mode: '0644'

    - name: Copy log-server.cfg to Nagios server
      ansible.builtin.copy:
        src: /tmp/ansible_fetched_files/log-server.cfg
        dest: /etc/nagios/servers/log-server.cfg
        owner: nagios
        group: nagios
        mode: '0644'

    - name: Copy web-server-1.cfg to Nagios server
      ansible.builtin.copy:
        src: /tmp/ansible_fetched_files/web-server-1.cfg
        dest: /etc/nagios/servers/web-server-1.cfg
        owner: nagios
        group: nagios
        mode: '0644'

    - name: Copy web-server-2.cfg to Nagios server
      ansible.builtin.copy:
        src: /tmp/ansible_fetched_files/web-server-2.cfg
        dest: /etc/nagios/servers/web-server-2.cfg
        owner: nagios
        group: nagios
        mode: '0644'

    - name: Verify copied files on Nagios server
      shell: ls -l /etc/nagios/servers/
      register: result

    - name: Show result of verification
      debug:
        var: result.stdout
    
    - name: Restart Nagios service
      service:
        name: nagios
        state: restarted
        enabled: yes