---
- name: Install and configure Nagios
  hosts: nagios_server
  become: yes
  roles:
    - change_hostname
    - configure_swap
    - configure_repositories
    - install_tools
    - deploy_scripts_and_files
    - nagios_setup
