    - name: Ensure /root/.ansible/tmp directory exists with correct permissions
      file:
        path: /root/.ansible/tmp
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Set hostname to match inventory name
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Update /etc/hostname
      lineinfile:
        path: /etc/hostname
        line: "{{ inventory_hostname }}"
        create: yes

    - name: Ensure the hostname is set in /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^127.0.0.1'
        line: "127.0.0.1 {{ inventory_hostname }}"
        create: yes
