- name: Install MariaDB Server
  yum:
    name: mariadb-server
    state: present

- name: Start and enable MariaDB service
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Install required Python packages
  yum:
    name:
      - python3-pip
    state: present

- name: Install development tools (gcc, make, etc.)
  yum:
    name:
      - gcc
      - make
      - mysql-devel
    state: present

- name: Install Python development headers
  yum:
    name: python3-devel
    state: present

- name: Install mysqlclient library for Python 3
  pip:
    name: mysqlclient
    state: present
    executable: /usr/bin/pip3

- name: Ensure MariaDB is started and listening
  wait_for:
    port: 3306
    state: started
    delay: 10
    timeout: 60

- name: Create MySQL database
  mysql_db:
    name: registration_app
    state: present
    login_user: root
    login_password: ""

- name: Create MySQL user with appropriate privileges
  mysql_user:
    name: admin
    password: password
    priv: "registration_app.*:ALL"
    host: "%"
    state: present
    login_user: root
    login_password: ""

- name: Grant privileges to admin user
  mysql_user:
    name: admin
    password: password
    priv: "registration_app.*:ALL"
    host: "%"
    state: present
    login_user: root
    login_password: ""

- name: Create users table
  mysql_query:
    login_user: root
    login_password: ""
    query: |
      CREATE TABLE IF NOT EXISTS registration_app.users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) NOT NULL UNIQUE
      );
- name: Create Nagios user with no password
  mysql_user:
    name: "nagios_user"
    host: "localhost"
    password: ""  # No password
    state: present
    priv: "*.*:SHOW DATABASES, SHOW TABLES, PROCESS, REPLICATION CLIENT" # Permissions required for monitoring
    login_user: root
    login_password: ""
    
# This task is to get the ip adderess of the database

- name: Get the private IP address of the database server
  command: hostname -I
  register: db_ip

- name: Write the IP address to a file on the controller
  local_action: copy content="{{ db_ip.stdout.split(' ')[0] | trim }}" dest="/tmp/db_ip.txt"
  run_once: true

