---
- name: Configure database server
  hosts: database_servers
  become: yes
  roles:
    - change_hostname
    - configure_swap
    - configure_repositories
    - install_tools
    - deploy_scripts_and_files
    - database_setup
