---
- name: Configure ansible server
  hosts: localhost
  become: yes
  roles:
    - change_hostname
    - configure_repositories
    - install_tools
    - deploy_scripts_and_files
    - ansible_node_setup